apiVersion: v1
kind: Service
metadata:
  name: {{ include "karbonite.fullname" . }}
  labels:
    {{- include "karbonite.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.controller.healthcheckPort }}
      targetPort: healthcheck
      protocol: TCP
      name: healthcheck
    - port : {{ .Values.controller.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "karbonite.selectorLabels" . | nindent 4 }}
