apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "karbonite.controller.clusterrole" . }}
  labels:
    app.kubernetes.io/component: rbac
    {{- include "karbonite.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "karbonite.controller.clusterrole" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "karbonite.serviceAccountName" . }}
    namespace: '{{ .Release.Namespace }}'
