apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "karbonite.leaderelection.role" . }}
  labels:
    app.kubernetes.io/component: rbac
    {{- include "karbonite.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "karbonite.leaderelection.role" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "karbonite.serviceAccountName" . }}
    namespace: '{{ .Release.Namespace }}'
