# permissions for end users to view hibernationrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hibernationrule-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: karbonite
    app.kubernetes.io/part-of: karbonite
    app.kubernetes.io/managed-by: kustomize
  name: hibernationrule-viewer-role
rules:
- apiGroups:
  - rules.karbonite.io
  resources:
  - hibernationrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rules.karbonite.io
  resources:
  - hibernationrules/status
  verbs:
  - get
