# permissions for end users to edit hibernationrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hibernationrule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: karbonite
    app.kubernetes.io/part-of: karbonite
    app.kubernetes.io/managed-by: kustomize
  name: hibernationrule-editor-role
rules:
- apiGroups:
  - karbonite.io
  resources:
  - hibernationrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - karbonite.io
  resources:
  - hibernationrules/status
  verbs:
  - get
