---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - deployments
  - statefulsets
  verbs:
  - update
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - karbonite.io
  resources:
  - deletionrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - karbonite.io
  resources:
  - deletionrules/finalizers
  verbs:
  - update
- apiGroups:
  - karbonite.io
  resources:
  - deletionrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - karbonite.io
  resources:
  - throttlingrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - karbonite.io
  resources:
  - throttlingrules/finalizers
  verbs:
  - update
- apiGroups:
  - karbonite.io
  resources:
  - throttlingrules/status
  verbs:
  - get
  - patch
  - update
