name: Docker buildx and push

on:
  push:
    tags:
      - "*"

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build and push Docker image
        run: make docker-buildx

  helm-push:
    needs: docker-buildx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Push Helm Chart to ChartMuseum
        uses: bsord/helm-push@4.2.0
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
          registry-url: 'oci://registry-1.docker.io/steromano'
          useOCIRegistry: true
          force: true
          chart-folder: charts
