name: Docker buildx and push

on:
  push:
    tags:
      - "*"

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build and push Docker image
        run: make docker-buildx
        env:
          KARBONITE_VERSION: "${{ github.ref_name }}"

  helm-push:
    needs: docker-buildx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Bump Helm chart version and appVersion to current tag
        run: |
          sed -i -E 's/^version: .+/version: ${{ github.ref_name }}/g' charts/karbonite/Chart.yaml
          sed -i -E 's/^appVersion: .+/appVersion: "${{ github.ref_name }}"/g' charts/karbonite/Chart.yaml

      - name: Push Helm Chart to DockerHub OCI registry
        uses: appany/helm-oci-chart-releaser@v0.4.0
        with:
          name: karbonite
          repository: steromano
          tag: "${{ github.ref_name }}"
          registry: registry-1.docker.io
          registry_username: "${{ secrets.DOCKERHUB_USERNAME }}"
          registry_password: "${{ secrets.DOCKERHUB_TOKEN }}"
